services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: uthmanmohamed
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  backend:
    build: backend
    ports:
      - "8080:8080"

networks:
  postgres:
    driver: bridge

volumes:
  postgres: